"Device Location report"
type DeviceLocationReportedEvent {
  "Device ID"
  id: String
  "Timestamp when the device sent its location"
  timestamp: BigInt
  "Longitude coordinates"
  lng: Float
  "Latitude coordinates"
  lat: Float
  "Hostname of the device"
  hostname: String
}

type Query {
  "Get a report summary of location devices."
  getDevicesLocation(page: Int, count: Int): [DeviceLocationReportedEvent]
}

type Subscription {
  deviceLocationReportedEvent: DeviceLocationReportedEvent
}