"Device Location report"
type DeviceLocationReportedEvent {
  "Device ID"
  deviceId: Int
  "Timestamp when the device sent its location"
  timeStamp: BigInt
  "Longitude coordinates"
  lng: Float
  "Latitude coordinates"
  lat: Float
  "License plate of the vehicle"
  plate: String
}

type Query {
  "Get a report summary of location devices."
  getDevicesLocation(page: Int, count: Int): [DeviceLocationReportedEvent]
}

type Subscription {
  deviceLocationReportedEvent: DeviceLocationReportedEvent
}